# @see https://docs.github.com/en/actions
# @see https://github.com/marketplace?verification=verified_creator&type=actions
env:
  NODEJS_VERSION: 26

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: "Runtime"
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - name: "Pull"
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: "Install"
        run: |
          npm ci
      - name: "Build"
        run: |
          npm run build
      - name: "Verify"
        run: |
          npm run verify

name: "CI"

# @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
