# @see https://docs.github.com/en/actions
# @see https://github.com/marketplace?verification=verified_creator&type=actions
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull repository."
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Install Node.js runtime."
        uses: actions/setup-node@v4
        with:
          node-version: "22.21.1"
      - name: "Install."
        run: |
          npm install
      - name: "Build."
        run: |
          npm run build

name: "CI"

# @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    types:
      - closed
      - reopened
  push:
