# @see https://docs.github.com/en/actions
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull repository."
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Install Node.js runtime."
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.0"
      - name: "Install dependencies."
        run: |
          npm install
      - name: "Build solution."
        run: |
          npm run build

name: "CI"

# @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
  push:
